# Generated by Django 5.2.8 on 2025-11-20 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=25, null=True)),
                ('memory_capacity', models.CharField(max_length=10, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('price_promotion', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_diagonal', models.FloatField(max_length=4, null=True)),
                ('display_resolution', models.CharField(max_length=20, null=True)),
                ('series', models.CharField(max_length=50, null=True)),
                ('seller', models.CharField(max_length=255, null=True)),
                ('product_code', models.IntegerField(null=True)),
                ('reviews_amout', models.IntegerField(null=True)),
                ('characteristics', models.JSONField(default=[], null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None)),
            ],
        ),
    ]
