# Generated by Django 5.2.8 on 2025-11-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='reviews_amout',
            new_name='reviews_amount',
        ),
    ]
