# Generated by Django 5.2.8 on 2025-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_reviews_amout_phone_reviews_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
