# Generated by Django 5.2.8 on 2025-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_phone_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='screen_diagonal',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
