# Generated by Django 5.2.8 on 2025-11-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_phone_screen_diagonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='series',
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
