# Generated by Django 5.2.8 on 2025-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_remove_phone_series_alter_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(default='New'),
        ),
    ]
