# Generated by Django 5.2.8 on 2025-11-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_phone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
